### ISSUE TITLE
Show comments on each issue in the issue log shows all comments

### ISSUE THREAD

**Issue by johnoro** [classroom-angel/labs11_prop_mngmt-FE#124]
Currently, 'Show Comments' on any single issue in the Issue Log view is toggling every single issue's comments. This probably isn't the desired response to this action. If it is, then there should be only one show comments button at the top.

Feel free to reproduce by:
1. going to https://www.classroomangel.us/issue-log
2. clicking `show comments` on any issue
3. observing that all issues' comments are showing instead of that particular issue's comments only

**Comment by johnoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show comments on each issue in the issue log shows all comments](https://trello.com/c/zL6HXck4/102-show-comments-on-each-issue-in-the-issue-log-shows-all-comments)

**Comment by grantreighard** [comment]
Fixed.
