### ISSUE TITLE
Typing in Add Comment in Issue Log view applies to all comment boxes

### ISSUE THREAD

**Issue by johnoro** [classroom-angel/labs11_prop_mngmt-FE#125]
Adding a comment to an issue in the Issue Log view seems to update all inputs for comments on the page. This is partially related to #124 

Reproduce:
1. Go to https://www.classroomangel.us/issue-log
2. Show Comments on any issue.
3. Type within the add comment box of any issue.
4. Observe that all other add comment boxes are updated.

(When you submit, it still only applies to the box that you submitted it on; this could be a different 'add comment' box than you typed it in.)

**Comment by johnoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Typing in Add Comment in Issue Log view applies to all comment boxes](https://trello.com/c/2oAq1f7o/104-typing-in-add-comment-in-issue-log-view-applies-to-all-comment-boxes)

**Comment by grantreighard** [comment]
Fixed.
