### ISSUE TITLE
Place the New Issue form for issue creation in the Issue Log view first

### ISSUE THREAD

**Issue by johnoro** [classroom-angel/labs11_prop_mngmt-FE#128]
The new issue form in the Issue Log view ought to be placed first. This has been mentioned already, but I thought we ought to go ahead and get it down somewhere!

See: https://www.classroomangel.us/issue-log for reference

**Comment by johnoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Place the New Issue form for issue creation in the Issue Log view first](https://trello.com/c/wPLeAEGc/107-place-the-new-issue-form-for-issue-creation-in-the-issue-log-view-first)

**Comment by TheDeterminator** [comment]
Done
