### ISSUE TITLE
Filter by tag and status seem to be MIA

### ISSUE THREAD

**Issue by johnoro** [classroom-angel/labs11_prop_mngmt-FE#129]
I'm not sure if this is somehow just me, but filtering options seem to be MIA. All I have is the text for them up top, no dropdowns or options.
https://www.classroomangel.us/issue-log
This happens for me in Chrome and Firefox so I'm assuming it's not an isolated issue.

**Comment by johnoro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filter by tag and status seem to be MIA in Issue Log view](https://trello.com/c/hvdb8pCK/108-filter-by-tag-and-status-seem-to-be-mia-in-issue-log-view)

**Comment by TheDeterminator** [comment]
Not just you. The select elements disappeared when we added materialize. I have since updated them with Dropdown components. You may encounter more bugs when using them, they should show up/be minimally functional now.
